{{- with .Values.migrator }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{- include "dotbot.fullname" $ }}-migrator"
  labels:
    {{- include "dotbot.labels" $ | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "dotbot.labels" $ | nindent 8 }}
        {{- with .podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: Never
      {{- if $.Values.serviceAccount.create }}
      serviceAccountName: "{{- include "dotbot.name" $ }}"
      {{- end }}
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      containers:
        - name: "{{- include "dotbot.name" $ }}-migrator"
          securityContext:
            {{- toYaml .securityContext | nindent 12 }}
          image: {{ .image.registry }}/{{ .image.repository }}:{{ .image.tag | default $.Chart.AppVersion }}{{ if .image.digest }}@{{ .image.digest }} {{ end }}
          imagePullPolicy: {{ .image.imagePullPolicy }}
          envFrom:
            - secretRef:
                name: {{ (tpl $.Values.existingMigratorSecret .) | default ((printf "%s-%s-%s" (include "dotbot.fullname" $) "migrator" "secret")) }}
          env:
            - name: DOTNET_BUNDLE_EXTRACT_BASE_DIR
              value: /cache
          volumeMounts:
            {{- toYaml .volumeMounts | nindent 12 }}
      volumes:
        {{- toYaml .volumes | nindent 8 }}
{{- end }}
