version: '3.8'

services:
  dotbot:
    container_name: dotbot
    image: dotbot
    build: "../src"
    environment:
      Discord__BotToken: ""
      MongoDbSettings__ConnectionString: "mongodb://mongo1:27017"
  mongo1:
    container_name: mongo1
    hostname: mongo1
    image: docker.io/library/mongo:6
    volumes:
      - mongodata1:/data/db
    expose:
      - 27017
    links:
      - mongo2
      - mongo3
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo2:
    container_name: mongo2
    image: docker.io/library/mongo:6
    volumes:
      - mongodata2:/data/db
    expose:
      - 27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
  mongo3:
    container_name: mongo3
    image: docker.io/library/mongo:6
    volumes:
      - mongodata3:/data/db
    expose:
      - 27017
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]

  mongosetup:
    image: mongo-setup
    build: "."
    container_name: mongosetup
    depends_on:
      mongo1:
        condition: service_started
    volumes:
      - mongostatus:/data/
  
volumes:
  mongodata1:
  mongodata2:
  mongodata3:
  mongostatus: